apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argorollout
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sonukeshri/myargo.git
    targetRevision: HEAD
    path: test
  destination: 
    server: https://kubernetes.default.svc
    namespace: testrollout

  syncPolicy:
    syncOptions:
    - CreateNamespace=false

    automated:
      selfHeal: true
      prune: true
